#!/usr/bin/evn bash



function hpicadd() {
	sourcePicPath="~/Pictures/"
	destPicPath="~/CGDB/houdiniDB/"
	picDBDir="picDB"
	dbFileName="picDataDB"
	DELIMITER="--DELIMITER--"

	if [ $# -eq 0 ]; then
		return 1
	fi
	fileName=`ls -t $sourcePicPath | head -n 1`
	mv "$sourcePicPath$fileName" "$destPicPath$picDBDir"
	echo -e $DELIMITER >> $destPicPath$dbFileName
	echo "$destPicPath$picDBDir/$fileName" >> $destPicPath$dbFileName
	echo -e $@ >> $destPicPath$dbFileName
	echo -e $DELIMITER >> $destPicPath$dbFileName
	echo "success"

}
