#!/usr/bin/env bash
SEARCHPATH="~/CGDB/houdiniDB/"
FILENAME="picDataDB"
DELIMITER="\-\-DELIMITER\-\-"

function hpicfind() {
	if [ $# -ne 1 ]; then
		echo "invalid arg number, 1 arg required." 1>&2
		return 1
	fi
	VAR=`cat $SEARCHPATH$FILENAME |  grep $1 -n -i | sed -e 's/:.*//g'`
	targetRows=($VAR)
	for targetRow in "${targetRows[@]}"
	do
		echo $targetRow
		startRow=`head -n $targetRow $SEARCHPATH$FILENAME | grep $DELIMITER -n | sed -e 's/:.*//g' | tail -n 1`
		rowNum=`cat $SEARCHPATH$FILENAME | wc -l`
		endRow=`tail -n $(($rowNum-$targetRow)) $SEARCHPATH$FILENAME | grep $DELIMITER -n | sed -e 's/:.*//g' | head -n 1`
		endRow=$(($endRow+$targetRow-1))
		PicPath=`cat $SEARCHPATH$FILENAME | head -n $endRow | tail -n $(($endRow-$startRow)) | head -n 1`
		xdg-open "$PicPath"
	done

}

